[profile.default]
src = "src"
out = "out"
libs = ["dependencies"] 
test = "test"


[dependencies]
forge-std = { version = "1.8.2" }
solmate = { version = "6.7.0" }
"@openzeppelin-contracts" = { version = "5.0.2" }
"@openzeppelin-contracts-upgradeable" = { version = "5.0.2" }
murky = "0.1.0"
